import json
from services.llm import call_llm
from typing import Any, Dict, List

SYNTHESIZER_PROMPT = """
You are the Synthesis Agent. You have received a complete event simulation —
a timeline of real events generated by multiple actors in the user's world.

Your job:
1. ANALYZE: What story does this timeline tell? What are the turning points?
2. IDENTIFY: What are the 3 most critical moments that define success or failure?
3. ASSESS: What is the most likely 12-month outcome given these events?
4. CONCLUDE: Give a direct, honest verdict — should they do this? Under what conditions?

Return ONLY valid JSON:
{
  "verdict": "2-3 sentence direct verdict. Be honest, not hedging.",
  "most_likely_outcome": "One paragraph narrative of the most probable 12-month story",
  "turning_points": [
    {"month": 3, "event": "The moment that determines success or failure", "why": "reason this is critical"}
  ],
  "key_risks": ["Top 3 risks from the simulation, most critical first"],
  "key_opportunities": ["Top 3 opportunities, most valuable first"],
  "risk_score": 65,
  "first_step": "The single most important concrete action to take in the next 7 days",
  "conditions_for_success": "What specific conditions would need to be true for this to work",
  "agent_consensus": "One sentence on where actors agreed, one sentence on biggest tension"
}

risk_score: 0=safe, 100=extreme risk.
Weight: financial exposure 40%, reversibility 30%, support system 20%, time pressure 10%.

Be specific. Reference actual events from the simulation. No generic advice.
Do not include any text outside the JSON.
"""


async def synthesize(
    events_by_actor: List[Dict[str, Any]],
    profile_summary: str,
    decision: str,
) -> Dict[str, Any]:
    # Build a readable event log to feed the synthesizer
    event_log = []
    for actor_data in events_by_actor:
        actor_name = actor_data.get("actor", "Unknown")
        for ev in actor_data.get("events", []):
            event_log.append(
                f"Month {ev.get('month', '?')} | {actor_name}: {ev.get('event', '')} "
                f"[{ev.get('impact', '')}] {ev.get('financial_delta', '') or ''} — {ev.get('detail', '')}"
            )

    event_log.sort()  # sorts by "Month X" prefix
    event_log_text = "\n".join(event_log)

    context = {
        "profile": profile_summary,
        "decision": f"{decision}\n\nFULL EVENT SIMULATION:\n{event_log_text}",
    }

    result = await call_llm(
        system_prompt=SYNTHESIZER_PROMPT,
        context=context,
        history=[],
        max_tokens=2000,
        agent_name="Synthesizer",
        model="gpt-4o",
    )

    raw = result["response"]
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    try:
        return json.loads(raw.strip())
    except json.JSONDecodeError:
        return {"verdict": "Synthesis failed.", "raw": raw[:500]}
