import json
from services.llm import call_llm
from agents.json_utils import extract_json_from_response
from typing import Any, Dict, List

SYNTHESIZER_PROMPT = """
You are the Synthesis Agent. You have received a complete event simulation —
a timeline of real events generated by multiple actors in the user's world.

Your job:
1. ANALYZE: What story does this timeline tell? What are the turning points?
2. IDENTIFY: What are the 3 most critical moments that define success or failure?
3. ASSESS: What is the most likely 12-month outcome given these events?
4. CONCLUDE: Give a direct, honest verdict — should they do this? Under what conditions?

Return ONLY valid JSON:
{
  "verdict": "2-3 sentence direct verdict. Be honest, not hedging.",
  "most_likely_outcome": "One paragraph narrative of the most probable 12-month story",
  "turning_points": [
    {"month": 3, "event": "The moment that determines success or failure", "why": "reason this is critical"}
  ],
  "key_risks": ["Top 3 risks from the simulation, most critical first"],
  "key_opportunities": ["Top 3 opportunities, most valuable first"],
  "risk_score": 65,
  "first_step": "The single most important concrete action to take in the next 7 days",
  "conditions_for_success": "What specific conditions would need to be true for this to work",
  "agent_consensus": "One sentence on where actors agreed, one sentence on biggest tension"
}

risk_score: 0=safe, 100=extreme risk.
Weight: financial exposure 40%, reversibility 30%, support system 20%, time pressure 10%.

Be specific. Reference actual events from the simulation. No generic advice.
Do not include any text outside the JSON.
"""


async def synthesize(
    events_by_actor: List[Dict[str, Any]],
    profile_summary: str,
    decision: str,
) -> Dict[str, Any]:
    # Build a readable event log to feed the synthesizer
    # NOTE: GitHub gpt-4o endpoint can reject large request bodies (413, ~8k-token limit).
    # We prioritize critical events and cap payload size before sending.
    MAX_EVENTS_FOR_SYNTHESIS = 70
    MAX_EVENT_LOG_CHARS = 12000

    event_rows = []
    for actor_data in events_by_actor:
        actor_name = actor_data.get("actor", "Unknown")
        for ev in actor_data.get("events", []):
            month = ev.get("month", 99)
            impact = ev.get("impact", "")
            financial = ev.get("financial_delta", "") or ""
            line = (
                f"Month {month} | {actor_name}: {ev.get('event', '')} "
                f"[{impact}] {financial} — {ev.get('detail', '')}"
            )

            priority = 0
            if impact == "negative":
                priority += 4
            elif impact == "positive":
                priority += 2
            if financial:
                priority += 3
            if month in (1, 2, 11, 12):
                priority += 2

            event_rows.append({
                "month": month if isinstance(month, int) else 99,
                "priority": priority,
                "line": line,
            })

    # Keep highest-priority rows, then restore chronological order.
    event_rows.sort(key=lambda r: (r["priority"], -r["month"]), reverse=True)
    event_rows = event_rows[:MAX_EVENTS_FOR_SYNTHESIS]
    event_rows.sort(key=lambda r: r["month"])

    # Hard cap by characters to avoid model request-size errors.
    event_log_lines = []
    char_count = 0
    for row in event_rows:
        line = row["line"]
        projected = char_count + len(line) + 1
        if projected > MAX_EVENT_LOG_CHARS:
            break
        event_log_lines.append(line)
        char_count = projected

    event_log_text = "\n".join(event_log_lines)
    print(
        f"[Synthesizer] events_in={sum(len(a.get('events', [])) for a in events_by_actor)} "
        f"selected={len(event_rows)} emitted={len(event_log_lines)} chars={len(event_log_text)}"
    )

    context = {
        "profile": profile_summary,
        "decision": f"{decision}\n\nFULL EVENT SIMULATION:\n{event_log_text}",
    }

    result = await call_llm(
        system_prompt=SYNTHESIZER_PROMPT,
        context=context,
        history=[],
        max_tokens=2000,
        agent_name="Synthesizer",
        model="gpt-4o-mini",
    )

    raw = result["response"]
    
    parsed = extract_json_from_response(raw, "Synthesizer")
    if "error" in parsed:
        return {"verdict": "Synthesis failed.", "error_message": parsed["error"]}
    
    return parsed
